import 'dart:convert';
import 'dart:io';

String processServiceFile(File file) {
  String jsonData = file.readAsStringSync();
  var jsonMap = jsonDecode(jsonData);

  var serviceName = jsonMap['someip'].keys.first;
  var service = jsonMap['someip'][serviceName];
  var serviceId = service['service_id'];
  var methods = service['methods'];
  var events = service['events'];

  Map<String, dynamic> serviceData = {
    "serviceName": serviceName,
    "serviceId": serviceId,
  };

  if (methods != null && (methods as Map).isNotEmpty) {
    serviceData["methods"] = methods.entries.map((entry) {
      return {
        "name": entry.key,
        "id": entry.value['id'],
        "in_type": entry.value['data_structure']['in']['type'],
      };
    }).toList();
  }

  if (events != null && (events as Map).isNotEmpty) {
    serviceData["events"] = events.entries.map((entry) {
      return {
        "name": entry.key,
        "id": entry.value['id'],
      };
    }).toList();
  }

  var encoder = const JsonEncoder.withIndent('  ');
  String prettyJson = encoder.convert(serviceData);

  return 'final Map<String, dynamic> $serviceName = $prettyJson;';
}

void main() async {
  final envPath = Platform.environment['SYSTEM_DEFINITION_ROOT'];
  final candidates = <String>[
    if (envPath != null && envPath.isNotEmpty) envPath,
    '../system_definition/someip',
    'system_definition/someip',
  ];

  Directory? someipDir;
  for (final path in candidates) {
    final dir = Directory(path);
    if (dir.existsSync()) {
      someipDir = dir;
      break;
    }
  }

  if (someipDir == null) {
    stderr.writeln(
      'System definition directory not found. Tried: ${candidates.join(", ")}',
    );
    exit(1);
  }

  List<File> serviceFiles = someipDir
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('service.json'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final out = StringBuffer();
  out.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  out.writeln(
    '// This file is generated by lib/generate/generate_data.dart',
  );
  out.writeln();

  for (File file in serviceFiles) {
    try {
      out.writeln(processServiceFile(file));
      out.writeln();
    } catch (e) {
      stderr.writeln('Error processing ${file.path}: $e');
    }
  }

  final outputFile = File('lib/views/generated_services.dart');
  outputFile.writeAsStringSync(out.toString());
  stdout.writeln(
    'Generated ${outputFile.path} from ${serviceFiles.length} service definitions.',
  );
}
